'use client';
import React from 'react';
import { CartesianGrid, Line, LineChart, XAxis } from "recharts"
import {
    Card,
    CardContent,
    CardHeader,
    CardTitle,
    CardDescription,
    CardFooter
} from "@/components/ui/card"
import {
    ChartTooltip,
    ChartTooltipContent,
    ChartContainer,
    ChartConfig
} from "@/components/ui/chart"

const tripData = [
    { name: 'Jan', uv: 4000 },
    { name: 'Feb', uv: 3000 },
    { name: 'Mar', uv: 2000 },
    { name: 'Apr', uv: 2780 },
    { name: 'May', uv: 1890 },
    { name: 'Jun', uv: 2390 },
    { name: 'Jul', uv: 3490 }
];

const chartConfig = {
    desktop: {
        label: "Desktop",
        color: "hsl(var(--chart-1))",
    },
} satisfies ChartConfig

export default function TripsLineChart() {
    return (
        <Card>
            <CardHeader>
                <CardTitle>It's a line chart!</CardTitle>
                <CardDescription>Dope</CardDescription>
            </CardHeader>
            <CardContent>
                <ChartContainer config={chartConfig} className="min-h-[200px] w-full">
                    <LineChart data={tripData} margin={{
                        top: 20,
                        right: 20,
                        left: 20,
                        bottom: 10
                    }}>
                        <CartesianGrid vertical={false} />
                        <XAxis dataKey="name" />
                        <ChartTooltip
                            cursor={false}
                            content={<ChartTooltipContent hideLabel />}
                        />
                        <Line
                            dataKey="uv"
                            type="natural"
                            stroke="var(--color-desktop)"
                            strokeWidth={2}
                            dot={false}
                        />
                    </LineChart>
                </ChartContainer>
            </CardContent>
            <CardFooter>
                Showing some sample data generated by Copilot i have no idea what it is
            </CardFooter>
        </Card>
    );
}
